### ISSUE TITLE
Support for EPUB3 `navigator.epubReadingSystem`

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#120]
This should be implemented in navigator, but app should be able to specify the actual contents of the injected `navigator.epubReadingSystem` object.
http://www.idpf.org/epub/31/spec/epub-contentdocs.html#app-epubReadingSystem

**Comment by danielweck** [comment]
Test EPUB:
 https://github.com/readium/readium-js-viewer/blob/develop/epub_content/epubReadingSystem.epub

**Comment by danielweck** [comment]
NAME and VERSION are the most important fields.
Readium1 generates additional versioning information (not a standard feature, specific to the reading system):
https://readium.firebaseapp.com/?epub=epub_content%2FepubReadingSystem

**Comment by danielweck** [comment]
Please merge this PR ( https://github.com/edrlab/readium-desktop/pull/129 ) to update to the latest `r2-xxx-js` packages and correctly synchronize other dependencies.

The navigator API that allows the host app to specify the `navigator.epubReadingSystem` `name` + `version` information works in exactly the same way as the ReadiumCSS one, i.e. using a "pull" pattern via a "getter" function (see `setReadiumCssJsonGetter()`) which will be invoked by the underlying Electron/WebView/preload.js code, at the appropriate time.

Code example:
```typescript
import { setEpubReadingSystemJsonGetter } from "@r2-navigator-js/electron/renderer/index";
import { INameVersion } from "@r2-navigator-js/electron/renderer/webview/epubReadingSystem";

const getEpubReadingSystem: () => INameVersion = () => {
    return { name: "Readium2 Electron/NodeJS desktop app", version: "1.0.0-alpha2" };
};
setEpubReadingSystemJsonGetter(getEpubReadingSystem);
```

**Comment by JayPanoz** [comment]
If I may, a quick question: will docs provide guidance on setting name/version? 

A lot of Readium1-based apps are indeed sharing the same name, which completely defeats the purpose of the object: implementations sometimes varying greatly, it becomes kind of useless for a lot of use cases where sniffing the `epubReadingSystem` is the last resort.

**Comment by danielweck** [comment]
@JayPanoz see https://github.com/readium/readium-2/issues/67
