### ISSUE TITLE
failed to install the deb package on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by YKastell** [edrlab/readium-desktop#124]
message d'erreur de gdebi : 

Sélection du paquet readium-desktop précédemment désélectionné.
(Lecture de la base de données... 831838 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../readium-desktop_0.0.1-alpha1_amd64.deb ...
Dépaquetage de readium-desktop (0.0.1-alpha1) ...
Paramétrage de readium-desktop (0.0.1-alpha1) ...
**ln: **impossible de créer le lien symbolique '/usr/local/bin/readium-desktop': Aucun fichier ou dossier de ce type****
dpkg: erreur de traitement du paquet readium-desktop (--install) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.22-1ubuntu5.1) ...
Traitement des actions différées (« triggers ») pour bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Traitement des actions différées (« triggers ») pour mime-support (3.59ubuntu1) ...

**Comment by clebeaupin** [comment]
You need to install it with a sudoer user:
```
sudo dpkg -i readium-desktop_0.0.1-alpha1_amd64.deb
```

**Comment by clebeaupin** [comment]
We have tested the deb installation on many version of linux including ubuntu 16.04 and we don't face the same problem.
It's clearly a permission issue in your case:
```
ln: impossible de créer le lien symbolique '/usr/local/bin/readium-desktop': Aucun fichier ou dossier de ce type
```

Does anyone has the same issue: unable to install the deb package ?

**Comment by YKastell** [comment]
in fact the  /usr/local/bin did not exist on my Ubuntu Mate 16.04 PC (it
seems that it prefers to use a /usr/local/sbin)

I created the /usr/local/bin directory and the installation went fine

2018-03-29 10:55 GMT+02:00 Cyrille Lebeaupin <notifications@github.com>:

**Comment by clebeaupin** [comment]
It's strange that you don't have a /usr/local/bin?
It's a standard in linux distributions.
So if everything went fine I will close this issue
