### ISSUE TITLE
Are GitHub milestones (currently unmaintained) still relevant since GitHub Projects is now used to coordinate development objectives?

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#147]
For example, the GitHub Milestone named "Second public release" has no due date, and is only very partially completed (3% right now):
https://github.com/edrlab/readium-desktop/milestone/2

...whereas the GitHub Project named "V1.0.0-alpha.2" correctly reflects the current development status:
https://github.com/edrlab/readium-desktop/projects/2

Technically-speaking, can we tie Milestones to Projects? Or should we just drop Milestones altogether given their lack of usefulness? (in fact, right now the situation is even worse because Milestones actually add confusion)

Note: depending on the general Readium2 consensus, in the future we may in fact need to consider using ZenHub / Waffle in order to manage cross-repository issues (notably: dependencies on `r2-xxx-js` packages), cascading Pull Requests, "Epics", reporting, etc.
See related issue: https://github.com/edrlab/readium-desktop/issues/141

**Comment by clebeaupin** [comment]
I suggest we drop the github milestones because we do not use them.

**Comment by llemeurfr** [comment]
Ok for me. The positive experience we are gaining using Zenhub and its Releases on the Swift and Kotlin devs will certainly end up with the same move on the Readium Desktop front. We may move to Zenhub when we move the project to the Readium repo. Until then we can rely on Projects.

**Comment by clebeaupin** [comment]
Github projects can be cross projects. Why using ZenHub?

**Comment by llemeurfr** [comment]
Please discuss that in #141.
I guess we can close this Milestones issue.

**Comment by danielweck** [comment]
@llemeurfr the milestones still exist: https://github.com/edrlab/readium-desktop/milestones
:)
