### ISSUE TITLE
associative array with key = spineItem.title is not reliable

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#46]
I posted a comment for review in this Pull Request:
https://github.com/edrlab/readium-desktop/pull/41#pullrequestreview-96817969

...but it seems the branch associated with the PR has already been merged into `feature/next-v1`. 
So I am posting a separate issue to address this.

Direct code reference:
https://github.com/edrlab/readium-desktop/blob/5db60f8ac5b77c8d782ca9732dd41bd60f8f3cd6/src/renderer/components/ReaderApp.tsx#L552

**Comment by danielweck** [comment]
Note that although PR 41 was closed (unmerged), the issue still exists. I commented there:
https://github.com/edrlab/readium-desktop/pull/41#issuecomment-369163147

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/0a7c5059d0fe9a57e4468ddb37ebb07c89dab300

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
