### ISSUE TITLE
React unique iterator key should be on 'li', not 'a' element.

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#56]
`Warning: Each child in an array or iterator should have a unique "key" prop.`

https://github.com/edrlab/readium-desktop/blob/3b6895e99619a5954ce2c21ab7fb67609d46ed49/src/renderer/components/ReaderApp.tsx#L307

@Scarsniik

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/3d54200918887e318f4574183859d84852b6e22e

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
