### ISSUE TITLE
reader view: left/right keystrokes to activate previous/next commands (page turn)

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#64]

**Comment by danielweck** [comment]
The difficulty with this keyboard interaction is that keyboard focus may be located inside the EPUB content documents (HTML hosted in Electron webview(s)) or in the application's UI (top-level Electron BrowserWindow). Consequently, depending on whether the arrow key strokes are meant to be already captured by other content interactions (for example: text input, in-page games, etc.) the "page turn" command may be vetoed.

**Comment by danielweck** [comment]
```
    window.document.addEventListener("keydown", (ev: KeyboardEvent) => {
        if (ev.keyCode === 37) { // left
            navLeftOrRight(true);
        } else if (ev.keyCode === 39) { // right
            navLeftOrRight(false);
        }
    });
```

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/0fd221d2eda2724f60fc6c75f02bad40f722efbc

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
