### ISSUE TITLE
"Display Type" terminology (paginated vs. scroll)

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#66]
The current terms are "Document" and "Continue", should be instead: "Paginated" and "Scrolling".

**Comment by llemeurfr** [comment]
Paginated -> Paginé
Scrolled -> Défilé

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/0830afa2d9de52cffd3331ee3908b50871967bdd

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
