### ISSUE TITLE
UI crashes (blank screen) when using escape key to close popup menus (toolbar), or enter/return to select menu item

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#70]
`Uncaught TypeError: iconButton.setKeyboardFocus is not a function, The above error occurred in the <IconMenu> component`
(material UI)

**Comment by danielweck** [comment]
CTRL-R to reload the page works

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/6da8b808a7300ae7688df305d6e6ee422a8b2099

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
