### ISSUE TITLE
Font chooser / selector: ReadiumCSS built-in (inc. Dyslexic), and system

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#86]
UI suggestion: https://github.com/reactjs/react-autocomplete

**Comment by danielweck** [comment]
`import SystemFonts = require("system-font-families");`

https://www.npmjs.com/package/system-font-families

**Comment by danielweck** [comment]
For ReadiumCSS fonts:

https://github.com/edrlab/r2-testapp-js/blob/develop/src/electron/renderer/index.ts#L614-L647

https://github.com/edrlab/r2-testapp-js/blob/15ad9100d8e22cf35886e5fed78c453aad887ee6/src/electron/renderer/index.ts#L614-L647

**Comment by danielweck** [comment]
The built-in ReadiumCSS fonts `r2-navigator-js` understands are the following string enumeration, or any other valid CSS `font-family` name:

DUO, DYS, OLD, MODERN, SANS, HUMAN, MONO

**Comment by JayPanoz** [comment]
For reference, the original feature request for system fonts in the Readium CSS issue tracker: https://github.com/readium/readium-css/issues/22
