### ISSUE TITLE
LCP publications are always marked as expired

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/readium-desktop#95]
This is a regression. Test with a "buy", an active "loan" and an expired "loan" licence.

**Comment by Scarsniik** [comment]
Commit done

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/readium-desktop/commit/fa7c7a24da13ec9efc5e9afa9a0e948530a8f00e

**Comment by danielweck** [comment]
Re-opening, @clebeaupin (lead dev) will check and close.
